camera_node:
  ros__parameters:
    frame_rate_hz: 10
    image_folder: "/path/to/kitti/dataset/image/folder"

    camera_info:
      camera_matrix:
        fx: 718.856
        fy: 718.856
        cx: 607.1928
        cy: 185.2157
      dist_coeffs: [0.0, 0.0, 0.0, 0.0] # radial-tangential distortion
        k1: 0.0
        k2: 0.0
        p1: 0.0
        p2: 0.0
        k3: 0.0
      image_height: 376
      image_width: 1241
    
indirect_vslam_node:
  ros__parameters:
    feature_extractor:
      num_features: 2000

    place_recognition:
      input: "orbvoc.dbow3"
      top_k: 3
      ignore_last_n_keyframes: 10
      score_thresh: 0.02

    # Plugins
    feature_extractor_plugin_name: "vslam_feature_extractor_plugins::OpenCVFeatureExtractor"
    feature_matcher_plugin_name: "vslam_feature_matcher_plugins::OpenCVFeatureMatcher"
    camera_tracker_plugin_name: "vslam_camera_tracker_plugins::IndirectTracker"
    mapper_plugin_name: "vslam_mapper_plugins::OpenCVTriangulation"
    backend_plugin_name: "vslam_backend_plugins::IndirectOptimizer"
    place_recognition_plugin_name: "vslam_place_recognition_plugins::BagOfWords"
    visualizer_plugin_name: "vslam_visualizer_plugins::RViz"