camera_node:
  ros__parameters:
    frame_rate_hz: 10
    image_folder: "/Users/sy/kitti/00/image_2"
    
indirect_vslam_node:
  ros__parameters:
    num_features: 1000
    camera_params:
      fx: 718.856
      fy: 718.856
      cx: 607.1928
      cy: 185.2157
    feature_extractor_plugin_name: "vslam_feature_extractor_plugins::Orb"
    feature_matcher_plugin_name: "vslam_feature_matcher_plugins::Orb"
    camera_tracker_plugin_name: "vslam_camera_tracker_plugins::Indirect"
    mapper_plugin_name: "vslam_mapper_plugins::OpenCvTriangulation"