camera_node:
  ros__parameters:
    plugin_name: "monocular_camera_plugins::VirtualCamera"
    params_file: "kitti_camera.yaml"
    
indirect_vslam_node:
  ros__parameters:
    feature_extractor:
      num_features: 2000

    place_recognition:
      input: "orbvoc.dbow3"
      top_k: 3
      ignore_last_n_keyframes: 10
      score_thresh: 0.02

    # Plugins
    feature_extractor_plugin_name: "vslam_feature_extractor_plugins::OpenCVFeatureExtractor"
    feature_matcher_plugin_name: "vslam_feature_matcher_plugins::OpenCVFeatureMatcher"
    camera_tracker_plugin_name: "vslam_camera_tracker_plugins::OpenCVCameraTracker"
    mapper_plugin_name: "vslam_mapper_plugins::OpenCVMapper"
    backend_plugin_name: "vslam_backend_plugins::IndirectOptimizer"
    place_recognition_plugin_name: "vslam_place_recognition_plugins::BagOfWords"
    visualizer_plugin_name: "vslam_visualizer_plugins::RViz"