camera_node:
  ros__parameters:
    frame_rate_hz: 10
    image_folder: "/path/to/kitti/dataset/image/folder"
    
indirect_vslam_node:
  ros__parameters:
    num_features: 2000
    
    camera_params:
      fx: 718.856
      fy: 718.856
      cx: 607.1928
      cy: 185.2157

    place_recognition:
      input: "orbvoc.dbow3"
      top_k: 3
      ignore_last_n_keyframes: 10
      score_thresh: 0.02

    # Plugins
    feature_extractor_plugin_name: "vslam_feature_extractor_plugins::Orb"
    feature_matcher_plugin_name: "vslam_feature_matcher_plugins::Orb"
    camera_tracker_plugin_name: "vslam_camera_tracker_plugins::Indirect"
    mapper_plugin_name: "vslam_mapper_plugins::OpenCvTriangulation"
    backend_plugin_name: "vslam_backend_plugins::Indirect"
    place_recognition_plugin_name: "vslam_place_recognition_plugins::BagOfWords"