# Get the keyframe with the provided frame id
# frame_id==-1 returns the current keyframe
# In relocalization mode, place recognition node may
# returns the frame id which can be used retrieve
# the candidate keyframe for relocalization
int64 frame_id
---
vslam_msgs/Frame keyframe
# Return true if a keyframe is found
bool has_keyframe